del "dbhr_insert.sql"
python3 csv_to_sql_insert.py "countries.csv" "countries"
python3 csv_to_sql_insert.py "departments.csv" "departments"
python3 csv_to_sql_insert.py "regions.csv" "regions"
python3 csv_to_sql_insert.py "job_history.csv" "job_history"
python3 csv_to_sql_insert.py "jobs.csv" "jobs"
python3 csv_to_sql_insert.py "locations.csv" "locations"
python3 csv_to_sql_insert.py "employees.csv" "employees"