DROP DATABASE IF EXISTS dbhr;
CREATE DATABASE dbhr;
USE dbhr;

CREATE TABLE countries (
	COUNTRY_ID VARCHAR(255),
    COUNTRY_NAME VARCHAR(255),
    REGION_ID INTEGER
);

CREATE TABLE departments (
	DEPARTMENT_ID INTEGER,
    DEPARTMENT_NAME VARCHAR(255),
    MANAGER_ID INTEGER,
    LOCATION_ID INTEGER
);

CREATE TABLE regions (
	REGION_ID INTEGER,
    REGION_NAME VARCHAR(255)
);

CREATE TABLE job_history (
	EMPLOYEE_ID INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID VARCHAR(255),
    DEPARTMENT_ID INTEGER
);

CREATE TABLE jobs (
	JOB_ID VARCHAR(255),
    JOB_TITLE VARCHAR(255),
    MIN_SALARY INTEGER,
    MAX_SALARY INTEGER
);

CREATE TABLE locations (
	LOCATION_ID INTEGER,
    STREET_ADDRESS VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    CITY VARCHAR(255),
    STATE_PROVINCE VARCHAR(255),
    COUNTRY_ID VARCHAR(255)
);

CREATE TABLE employees (
	EMPLOYEE_ID INTEGER,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(255),
    SALARY INTEGER,
    COMMISSION_PCT FLOAT,
    MANAGER_ID INTEGER,
    DEPARTMENT_ID INTEGER
);
